### ISSUE TITLE
EEPROM.write

### ISSUE THREAD

**Issue by bgcampbell** [tgolla/EEPROMTyped#1]
I suggest you change EEPROM.write() to EEPROM.update(). The latter only writes if the data already stored is different. Given that the EEPROM has a life of 100,000 cycles, this will extend the life of the chip especially if the application does frequent writes. Also, if the data is unchanged, nothing is written making the operation faster. The EEPROM read time is negligible.

If you make this change ro the write() function but otherwise leave it, anyone's existing software will not break with the update.

PS. I've made this change on my copy and it seems to work fine.

**Comment by tgolla** [comment]
Without an architecture decision record, it’s hard to say why the orginal EEPROM library has a read(), write() and update(). My guess was that the option to have both write() and update() was to offer the developer the slight speed advantage write() has over update(). Great from a flexibility standpoint, but not from the electrical engineering (EE) aspect which you pointed out, in that an EEPROM has a life of 100,000 cycles.

My take was to protect the programmer from their ignorance of EE and the call that seems more obvious…write() by baking this protection directly into the write call (see code).

```
if (EEPROM.read(address) != b)
        EEPROM.write(address++, b), ++p;
```
Ref: 
Documenting Architecture Decissions
https://www.cognitect.com/blog/2011/11/15/documenting-architecture-decisions
https://github.com/joelparkerhenderson/architecture-decision-record/blob/main/templates/decision-record-template-by-michael-nygard/index.md
